# Generated by Django 4.2.7 on 2025-03-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
    ]
