# Generated by Django 4.2.7 on 2025-03-03 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='AboutEvent',
        ),
        migrations.AlterModelTable(
            name='aboutevent',
            table='about_event',
        ),
    ]
